name: eat_now
description: Eat now, pay later

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  carousel_slider: ^2.1.0
  provider:
  google_fonts:
  animator: ^2.0.1
  image_picker:
  file_picker: ^1.12.0
  fluttertoast:
  shared_preferences:
  progress_dialog: ^1.2.2
  intl: ^0.16.0
  flutter_rounded_progress_bar: ^0.1.2
  flutter_paystack: ^1.0.3+1
  get_it: ^4.0.2
  rxdart: ^0.24.1
  introduction_screen: ^1.0.8
  flutter_launcher_icons: ^0.7.5
  smooth_star_rating: 1.1.1
  cached_network_image: ^2.2.0+1
  autocomplete_textfield: ^1.7.3

  firebase_database:
  firebase_auth:
  firebase_storage:


  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^0.1.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: "^0.7.3"

flutter_icons:
  android: true
  ios: true
  image_path: "assets/logo.png"

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/ob1.jpeg
    - assets/ob2.jpeg
    - assets/ob3.jpeg
    - assets/ob4.jpeg
    - assets/logo1.jpeg
    - assets/verify_img.jpg
    - assets/menu.png
    - assets/delete.png
    - assets/paystack.png
    - assets/home.png
    - assets/orders.png
    - assets/cart.png
    - assets/user.png
    - assets/wallet.png
    - assets/valtype.png
    - assets/logo.png
    - assets/not.png
    - assets/search.png
    - assets/rl1.jpg
    - assets/rl2.jpg
    - assets/rl3.jpg
    - assets/nofood.png
    - assets/call.png
    - assets/copy.png
    - assets/locate.png
    - assets/mastercard.png
    - assets/visa.png

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
